AWSTemplateFormatVersion: '2010-09-09'
Description: "This template creates a RDS for Mysql"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: RDS Configuration 
        Parameters:    
          - EnvType
          - DBInstanceIdentifier
          - DBName
          - DBMasterUserName
          - DBMasterUserPassword
          - EngineVersion 
          - InstanceClass
          - StorageSize 
          - MultiAZ

Parameters:
# ------------------------------------------------------------#
# 論理ID:Envタグ
# DB論理ID:DBInstanceIdentifier,DBName,DBMasterUserName,DBMasterUserPassword,EngineVersion
# RDS論理ID:InstanceClass,StorageSize ,MultiAZ
# ------------------------------------------------------------#
  EnvType: 
    Description: "Please type the Environment Type. Choose from dev, test, stg, prod."
    Type: String
    Default: "prod"
    AllowedValues:
      - "dev"
      - "test"
      - "stg"
      - "prod"
  DBInstanceIdentifier:
    Type: String
    Default: "CFntest-RDS-Mysql"
  DBName:
    Type: String
    Default: "CFntest" 
  DBMasterUserName:
    Type: String
    Default: "dbuser"
    NoEcho: true
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "The beginning is a character. Alphanumericals can be used."
  DBMasterUserPassword:
    Default: "dbpassword"
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: "Eight or more alphanumerical characters"
  EngineVersion:
    Type: String
    Description: "for Mysql"
    Default: "8.0.27"
  InstanceClass:
    Type: String
    Default: "db.t2.micro"
  StorageSize:
    Type: String
    Default: '10'
  MultiAZ: 
    Type: String
    Default: "false"  
    AllowedValues: [ "true", "false" ]  

Resources:
# ------------------------------------------------------------#
# DB SubnetGroup
# ------------------------------------------------------------#  
  DBSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: MyRails development
      DBSubnetGroupName: !Sub SubnetGroup-${DBInstanceIdentifier}-${EnvType}
      SubnetIds:
        - !ImportValue CFntest-Pri1aSubnet
        - !ImportValue CFntest-Pri1cSubnet 

  CFntestRDS:
# ------------------------------------------------------------#
# RDS
# ------------------------------------------------------------#  
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref StorageSize
      DBInstanceClass: !Ref InstanceClass
      DBInstanceIdentifier: !Ref DBInstanceIdentifier 
      DBName: !Ref DBName
      DBSubnetGroupName: !Ref DBSubnetGroup  
      Engine: mysql 
      EngineVersion: !Ref EngineVersion
      MasterUserPassword: !Ref DBMasterUserPassword
      MasterUsername: !Ref 'DBMasterUserName'
      PubliclyAccessible: 'false'
      MultiAZ: !Ref MultiAZ # 無料利用枠の範囲に収めるため、シングルAZ構成。
      VPCSecurityGroups:
        - !ImportValue CFntest-SG-RDS
      Tags: 
        - Key: Name
          Value: !Ref DBInstanceIdentifier
        - Key: EnvType
          Value: !Ref EnvType
    DeletionPolicy: Snapshot # シングルAZ構成のため、障害時はバックアップから復旧。    